server {
    server_name 51.91.108.173 taskflowpro.alvarezconsult.com;

    root /home/manuel/TASKFLOWPRO/dist;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    add_header X-Frame-Options "SAMEORIGIN";
    add_header X-Content-Type-Options "nosniff";

    access_log /var/log/nginx/taskflowpro.access.log;
    error_log  /var/log/nginx/taskflowpro.error.log;

    listen 8887 ssl; # Puerto solicitado por el usuario
    listen 443 ssl; # Mantenemos 443 por seguridad/conveniencia

    ssl_certificate /etc/letsencrypt/live/taskflowpro.alvarezconsult.com/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/taskflowpro.alvarezconsult.com/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}
server {
    if ($host = taskflowpro.alvarezconsult.com) {
        return 301 https://$host:8887$request_uri;
    } # managed by Certbot

    listen 80;
    server_name 51.91.108.173 taskflowpro.alvarezconsult.com;
    return 404; # managed by Certbot
}
